write:
  fields:
    element_id:
      required: true
      example: "sensor.boiler_temperature"
      selector:
        text:
    value:
      required: true
      example: "42.5"
      selector:
        object:
    quality:
      required: false
      example: "Good"
      selector:
        select:
          options:
            - "Good"
            - "GoodNoData"
            - "Bad"
            - "Uncertain"
    timestamp:
      required: false
      example: "2026-07-24 12:00:00"
      selector:
        datetime:
    config_entry_id:
      required: false
      selector:
        text:
